modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="thevikingway"
version="1.0.0"
displayName="The Viking Way"
authors="Mark and Karolinka"
description='''
A small Viking-themed mod.
'''
